name: Publish to NuGet
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Build, pack & publish
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@master
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: latest
    - run: nuget pack
    - run: nuget push ./*.nupkg -src https://nuget.org -SkipDuplicate  